#!/bin/bash


IP=`ifconfig wwan0 | grep inet[^6] | cut -d " " -f 10`

ID=`cat /home/pi/car_id.txt`

echo "$IP" > /tmp/${ID}.txt

runuser -l pi -c "scp /tmp/${ID}.txt ubuntu@signaling.voysys.se:~/rc_cars"

rm /tmp/${ID}.txt

